/*
 * File: app/view/Root.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Root', {
    extend: 'Ext.Container',

    config: {
        id: 'root',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'list',
                id: 'stationList',
                itemId: 'mylist',
                itemTpl: [
                    '<div>{key}</div>'
                ],
                store: 'stations',
                grouped: true,
                indexBar: true,
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'searchfield',
                                id: 'mysearchfield',
                                itemId: 'mysearchfield',
                                label: ''
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'list',
                id: 'departureTimeList',
                itemId: 'mylist1',
                itemTpl: [
                    '<div>{line} {direction} in {countdown} min</div>'
                ],
                store: 'departureTimes',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton',
                                text: 'zur Übersicht'
                            },
                            {
                                xtype: 'label',
                                flex: 1,
                                id: 'departureLabel'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMysearchfieldKeyup',
                event: 'keyup',
                delegate: '#mysearchfield'
            },
            {
                fn: 'onMysearchfieldClearicontap',
                event: 'clearicontap',
                delegate: '#mysearchfield'
            },
            {
                fn: 'onMylistSelect',
                event: 'select',
                delegate: '#stationList'
            },
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#mybutton'
            },
            {
                fn: 'onDepartureTimeListUpdateList',
                event: 'updateList',
                delegate: '#departureTimeList'
            },
            {
                fn: 'onRootChangeList',
                event: 'changeList'
            },
            {
                fn: 'onRootInitialize',
                event: 'initialize'
            },
            {
                fn: 'onRootGeopositionChangeD',
                event: 'geopositionChanged'
            }
        ]
    },

    onMysearchfieldKeyup: function(textfield, e, options) {
        if(this.filterTask === undefined)
        this.filterTask = new Ext.util.DelayedTask(this.executeSearch, this);

        this.filterTask.delay(300);
    },

    onMysearchfieldClearicontap: function(text, e, options) {
        if(this.filterTask === undefined)
        this.filterTask = new Ext.util.DelayedTask(this.executeSearch, this);

        this.filterTask.delay(0);
    },

    onMylistSelect: function(dataview, record, options) {
        Ext.getCmp("root").fireEvent("changeList", Ext.getCmp("departureTimeList"));
        Ext.getCmp("departureTimeList").fireEvent("updateList", record.get("swuid"));
        Ext.getCmp("departureLabel").location = record.get("key");
        Ext.getCmp("departureLabel").setHtml(Ext.getCmp("departureLabel").location);
    },

    onMybuttonTap: function(button, e, options) {
        Ext.getCmp("stationList").deselectAll();
        Ext.getCmp("root").fireEvent("changeList", Ext.getCmp("stationList"));
        Ext.getCmp("departureTimeList").swuid = undefined;
        clearInterval(Ext.getCmp("root").intervall);
    },

    onDepartureTimeListUpdateList: function(id) {
        Ext.getCmp("departureTimeList").swuid = id;
        Ext.getCmp("root").startReloadTask();
    },

    onRootChangeList: function(card) {
        this.setActiveItem(card);
        /*
        TODO
        reload von aktuem departue list
        suche auf wildcard ändern
        */
    },

    onRootInitialize: function(component, options) {
        Ext.require("Ext.device.Geolocation");
        Ext.device.Geolocation.watchPosition({
            frequency: 3000,
            success: function(position){
                component.fireEvent("geopositionChanged",{latitude: position.coords.latitude, longitude: position.coords.longitude});
            },
            failure: function(){
                alert("Fehlerhafte Ortung.");
                alert(JSON.stringify(arguments));
            }
        });

    },

    onRootGeopositionChangeD: function(opts, event) {
        var url = "/allByCoords?coords=" + JSON.stringify([opts.longitude, opts.latitude]);
        Ext.Ajax.request({
            url: url,
            success: function(response){

                var record = stationsStore.findRecord("group", "1. Nächste Stationen");
                while(record !== null){
                    stationsStore.remove(record);
                    record = stationsStore.findRecord("group", "1. Nächste Stationen");
                }

                var text = JSON.parse(response.responseText);
                var stationsStore = Ext.getCmp("stationList").getStore();
                var stationModel = stationsStore.getModel();
                for(var i = 0; i < text.rows.length ; i++){
                    var station = new stationModel();
                    station.set("swuid", text.rows[i].id);
                    station.set("key", text.rows[i].location);
                    station.set("value", text.rows[i].oldid);
                    station.set("group", "1. Nächste Stationen");
                    stationsStore.add(station);
                }
            }
        });
    },

    executeSearch: function() {
        var search = Ext.getCmp("mysearchfield").getValue().split(" ");
        Ext.getCmp("stationList").getStore().clearFilter();
        Ext.getCmp("stationList").getStore().filterBy(
        function(record){
            var key = record.get("key");
            for(var i in search){
                if(key.toLowerCase().indexOf(search[i].toLowerCase()) === -1)
                return;
            }
            return key;
        }
        );
    },

    startReloadTask: function() {
        var id = Ext.getCmp("departureTimeList").swuid;
        Ext.getCmp("departureTimeList").getStore().load({
            url: '/departure-times/' + id
        });

        var self = this;
        self.intervall = setInterval(function(){
            id = Ext.getCmp("departureTimeList").swuid;
            console.info(id);
            if(id === null || id === undefined){
                clearInterval(self.intervall);
            }else{
                Ext.getCmp("departureTimeList").getStore().load({
                    url: '/departure-times/' + id
                });
            }
        }, 20 * 1000);
    }

});